// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opmmqfileczrcokvxifd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wbW1xZmlsZWN6cmNva3Z4aWZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MjcxNjQsImV4cCI6MjA3NDAwMzE2NH0.-PNMyEvdxwyh8CQ_YJg7vceFJrIA7URoBfIBYwcB0P4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});